/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface':                   '#f7f9fb',
        'surface-dim':               '#d8dadc',
        'surface-bright':            '#f7f9fb',
        'surface-container-lowest':  '#ffffff',
        'surface-container-low':     '#f2f4f6',
        'surface-container':         '#eceef0',
        'surface-container-high':    '#e6e8ea',
        'surface-container-highest': '#e0e3e5',
        'on-surface':                '#191c1e',
        'on-surface-variant':        '#444654',
        'inverse-surface':           '#2d3133',
        'inverse-on-surface':        '#eff1f3',
        'outline':                   '#747686',
        'outline-variant':           '#c4c5d6',
        'surface-tint':              '#3052d2',
        'primary':                   '#1a40c2',
        'on-primary':                '#ffffff',
        'primary-container':         '#3b5bdb',
        'on-primary-container':      '#e2e5ff',
        'inverse-primary':           '#b8c3ff',
        'secondary':                 '#006591',
        'on-secondary':              '#ffffff',
        'secondary-container':       '#39b8fd',
        'on-secondary-container':    '#004666',
        'tertiary':                  '#863700',
        'on-tertiary':               '#ffffff',
        'tertiary-container':        '#ac4900',
        'on-tertiary-container':     '#ffe0d2',
        'error':                     '#ba1a1a',
        'on-error':                  '#ffffff',
        'error-container':           '#ffdad6',
        'on-error-container':        '#93000a',
        'primary-fixed':             '#dde1ff',
        'primary-fixed-dim':         '#b8c3ff',
        'on-primary-fixed':          '#001355',
        'on-primary-fixed-variant':  '#0736ba',
        'secondary-fixed':           '#c9e6ff',
        'secondary-fixed-dim':       '#89ceff',
        'on-secondary-fixed':        '#001e2f',
        'on-secondary-fixed-variant':'#004c6e',
        'tertiary-fixed':            '#ffdbcb',
        'tertiary-fixed-dim':        '#ffb691',
        'on-tertiary-fixed':         '#341100',
        'on-tertiary-fixed-variant': '#793100',
        'background':                '#f7f9fb',
        'on-background':             '#191c1e',
        'surface-variant':           '#e0e3e5',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm:      '0.25rem',
        md:      '0.5rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        '2xl':   '1rem',
        full:    '9999px',
      },
      spacing: {
        xs:     '4px',
        sm:     '8px',
        md:     '16px',
        lg:     '24px',
        xl:     '32px',
        xxl:    '48px',
        gutter: '24px',
        margin: '32px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        'headline-xl': ['30px', { lineHeight: '38px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg':     ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md':     ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md':    ['12px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '500' }],
        'code-sm':     ['12px', { lineHeight: '18px', fontWeight: '400' }],
      },
      boxShadow: {
        card:   '0 1px 3px rgba(0,0,0,0.05)',
        float:  '0 10px 30px rgba(0,0,0,0.08)',
        bottom: '0 -2px 10px rgba(0,0,0,0.05)',
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/typography'),
  ],
};
